apiVersion: v1
kind: Service
metadata:
  name: java-web-service
spec:
  type: NodePort
  selector:
    app: java-web
  ports:
    - protocol: TCP
      port: 80         # Internal Cluster IP port
      targetPort: 8080 # Points to the Container Port
      nodePort: 30001  # Use this in your browser (No conflict with 8080!)
